[package]
name = "modules"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"sqoinlib" = "0.1.1"
"halimalib" = { path = "../halimalib" , version= "0.1.0" }
